package bsh;

public interface ParserTreeConstants {
  int JJTVOID = 0;
  int JJTCLASSDECLARATION = 1;
  int JJTMETHODDECLARATION = 2;
  int JJTPACKAGEDECLARATION = 3;
  int JJTIMPORTDECLARATION = 4;
  int JJTVARIABLEDECLARATOR = 5;
  int JJTARRAYINITIALIZER = 6;
  int JJTFORMALPARAMETERS = 7;
  int JJTFORMALPARAMETER = 8;
  int JJTTYPE = 9;
  int JJTRETURNTYPE = 10;
  int JJTPRIMITIVETYPE = 11;
  int JJTAMBIGUOUSNAME = 12;
  int JJTASSIGNMENT = 13;
  int JJTTERNARYEXPRESSION = 14;
  int JJTBINARYEXPRESSION = 15;
  int JJTUNARYEXPRESSION = 16;
  int JJTCASTEXPRESSION = 17;
  int JJTPRIMARYEXPRESSION = 18;
  int JJTMETHODINVOCATION = 19;
  int JJTPRIMARYSUFFIX = 20;
  int JJTLITERAL = 21;
  int JJTARGUMENTS = 22;
  int JJTALLOCATIONEXPRESSION = 23;
  int JJTARRAYDIMENSIONS = 24;
  int JJTBLOCK = 25;
  int JJTFORMALCOMMENT = 26;
  int JJTSWITCHSTATEMENT = 27;
  int JJTSWITCHLABEL = 28;
  int JJTIFSTATEMENT = 29;
  int JJTWHILESTATEMENT = 30;
  int JJTFORSTATEMENT = 31;
  int JJTENHANCEDFORSTATEMENT = 32;
  int JJTTYPEDVARIABLEDECLARATION = 33;
  int JJTSTATEMENTEXPRESSIONLIST = 34;
  int JJTRETURNSTATEMENT = 35;
  int JJTTHROWSTATEMENT = 36;
  int JJTTRYSTATEMENT = 37;
  String[] jjtNodeName = new String[]{"void", "ClassDeclaration", "MethodDeclaration", "PackageDeclaration", "ImportDeclaration", "VariableDeclarator", "ArrayInitializer", "FormalParameters", "FormalParameter", "Type", "ReturnType", "PrimitiveType", "AmbiguousName", "Assignment", "TernaryExpression", "BinaryExpression", "UnaryExpression", "CastExpression", "PrimaryExpression", "MethodInvocation", "PrimarySuffix", "Literal", "Arguments", "AllocationExpression", "ArrayDimensions", "Block", "FormalComment", "SwitchStatement", "SwitchLabel", "IfStatement", "WhileStatement", "ForStatement", "EnhancedForStatement", "TypedVariableDeclaration", "StatementExpressionList", "ReturnStatement", "ThrowStatement", "TryStatement"};
}
